### ISSUE TITLE
In the search bar, after hovering over the search hint, a white bar is displayed

### ISSUE THREAD

**Issue by konsternacja** [Falscify/falscify-web-app#16]
*Please read the following instructions carefully.*

*Having detailed, yet not overcomplicated feedback will help us resolve the issue efficiently.* 🚒

***Before reporting a bug, please search for a similar problem in the issues section.*** 👀️

### Checklist ✅

- [x] I have read and consent to this project's [Code of Conduct](https://github.com/f1lem0n/falscify/blob/main/CODE_OF_CONDUCT.md).
- [x] I added a very descriptive title.
- [x] I searched through issues in this repository to find a similar problem but did not find any.
- [x] I searched through **falscify** documentation and found no solutions.
- [x] I searched through Google and found no explanation.
- [x] I asked ChatGPT for help with this issue but did not get any helpful response.

### Bug description 📖

In the search bar, after hovering over the search hint, a white bar is displayed

### Instruction on how to reproduce this error

1. Open page http://falscify.pl/home

2. Click on the search bar

3. Click the left mouse button

4. Hover over the proposed text

Current result:
A white bar is displayed

Expected result:
Search bar doesn’t change

### Additional comments 💬

*You can provide some additional information in this section.*

<br>

*Thank you for your contribution!*

**Comment by f1lem0n** [comment]
Let's wait and see if it will update on live website

**Comment by f1lem0n** [comment]
OK! all the changes look good.

**Important note:** After uploading changes to the live server we have to clear a browser cache (in Chrome the shortcut is ctrl+F5)
